---
title: "Overview"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r set_path_and_file_names, include=FALSE}

path_cmorized <-
  "/net/kryo/work/loher/ROMS/RECCAP2/"


files <- c(
  "Atlantic/cmorized/RECCAP2_amacanc_Lp576.nc",
  "Pactcs30/cmorized/RECCAP2_pactcs30.nc",
  "Humpac15/cmorized/RECCAP2_humpac15.nc"
)

```

```{r load_libraries_specific, include=FALSE}
library(stars)
library(tidync)
library(units)
library(PCICt)
library(rnaturalearth)
library(rnaturalearthdata)

```

# Files

Following files were inspected:

```{r files}
print(path_cmorized)
print(files)
```

# Dimensions and maps

For all files, the dimensions and parameter values at the latest time step are shown below.

```{r plot_test_files, fig.asp=0.5}

world <- ne_countries(scale = "small", returnclass = "sf")

for (i_files in files) {
  # i_files <- files[2]
  
  # read in data
  variable_data <-
    read_ncdf(
      paste(path_cmorized,
            i_files,
            sep = ""),
      make_units = FALSE,
      make_time = TRUE
      #ncsub = cbind(start = c(1, 1, 1), count = c(2, 2, 2)),
      # var = "dissicos"
    )
  
  print(i_files)
  print(st_dimensions(variable_data))

  time_length <- st_dimensions(variable_data)$time$to
  time_max <- st_dimensions(variable_data)$time$values[time_length]

  
  variable_data <- variable_data %>%
    slice(index = time_length, along = time)
  
  attribute_names <- names(variable_data)

  for (i_attribute in attribute_names) {
    # i_attribute <- attribute_names[3]
    
    print(
    ggplot(data = world) +
      geom_stars(data = variable_data[i_attribute]) +
      geom_sf()  +
      coord_sf(expand = 0) +
      scale_fill_viridis_c() +
      labs(title = paste(i_files, "| time: ",time_max))
    )
    
  }
  
}


```

